### ISSUE TITLE
'Too many open files'

### ISSUE THREAD

**Issue by jftsang** [rpedde/tmfuse#1]
When I try to copy across a large number of files, the first few files are copied fine, but later files throw the complaint 'too many open files' and nothing is copied. When this happens, I have to unmount the drive and run tmfuse again before I can do anything else with the drive.

**Comment by goetzrieger** [comment]
To be expected... I had the same issue, adjusted number of open files by using ulimit temporarily in the shell the script is running in. YMMV depending on your Linux distro, though.

Apart from that... last update 2014, just used it on F29, worked like a charme. Thanks!

**Comment by nomeata** [comment]
Hit the same issue, thanks for the pointer with increasing `ulimit`.

But why is this expected? Is there an issue with the fuse module that doesn't close files in a timely manner?

**Comment by rpedde** [comment]
I took a brief perusal of the code and don't see obvious fd loss.  If I can find a time machine backup I may take a look at this over the weekend, maybe make that code py3 compatible as well since it surprisingly seems to still work.  I'll bump this issue if I find anything useful.

**Comment by rpedde** [comment]
There was indeed a fd leak.  Should be fixed now.  4 years from open -> resolution.  Good thing I'm not being paid on MTTR.
